development:
  adapter: postgresql
  encoding: unicode
  database: project_tracking_dev
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: project_tracking_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: project_tracking_production
  host: localhost
  pool: 5
  username: postgres
  password: postgres